name: Rust Continuous integration

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # Runs at 16:00 UTC on the 1st of every month
  schedule:
    - cron:  '0 16 1 * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: ${{ matrix.legs.Example }}
    strategy:
      fail-fast: false
      matrix:
        legs:
          - {Example: "blinky", Target: "thumbv7em-none-eabihf"}
          - {Example: "uart", Target: "thumbv7em-none-eabihf"}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          profile: minimal
          toolchain: stable
          target:  ${{ matrix.legs.Target }}
          override: true
      
      - name: Cargo build
        env:
          Example: ${{ matrix.legs.Example }}
        run: |
          cargo --version
          cd example/$Example
          cargo build --release --all-features
          
      - name: Upload Results
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        env:
          Example: ${{ matrix.legs.Example }}
          Target: ${{ matrix.legs.Target }}
        continue-on-error: True
        with:
          name: ${{ matrix.legs.Example }}
          path: example/$Example/target/$Target/release/$Example
